openapi: 3.1.0
info:
  version: 1.0.0
  title: <назва вашого додатку>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    <опис вашого додатку>
tags:
  - name: Products
    description: Operations with products
servers:
  - url: http://localhost:3000
  - url: https://nodejs-practice-2024-12-01.onrender.com
paths:
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
